version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"  # UI RabbitMQ
      - "1883:1883"    # MQTT RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: rabbitmq-plugins enable rabbitmq_mqtt --offline

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1884:1883"  # Mosquitto sur 1884
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro